name: CI build

# on push any branch
on:
  push:


jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: compile and build
        run: |
          mvn clean install